//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace BullBooks.ISBNWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ISBNSoap", Namespace="http://BullBooksWS.net/")]
    public partial class ISBN : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetBookByISBNOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetGenresTableOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateRatingOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddNewBookOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ISBN() {
            this.Url = global::BullBooks.Properties.Settings.Default.BullBooks_ISBNWS_ISBN;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetBookByISBNCompletedEventHandler GetBookByISBNCompleted;
        
        /// <remarks/>
        public event GetGenresTableCompletedEventHandler GetGenresTableCompleted;
        
        /// <remarks/>
        public event UpdateRatingCompletedEventHandler UpdateRatingCompleted;
        
        /// <remarks/>
        public event AddNewBookCompletedEventHandler AddNewBookCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://BullBooksWS.net/GetBookByISBN", RequestNamespace="http://BullBooksWS.net/", ResponseNamespace="http://BullBooksWS.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public WSBook GetBookByISBN(string isbn) {
            object[] results = this.Invoke("GetBookByISBN", new object[] {
                        isbn});
            return ((WSBook)(results[0]));
        }
        
        /// <remarks/>
        public void GetBookByISBNAsync(string isbn) {
            this.GetBookByISBNAsync(isbn, null);
        }
        
        /// <remarks/>
        public void GetBookByISBNAsync(string isbn, object userState) {
            if ((this.GetBookByISBNOperationCompleted == null)) {
                this.GetBookByISBNOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBookByISBNOperationCompleted);
            }
            this.InvokeAsync("GetBookByISBN", new object[] {
                        isbn}, this.GetBookByISBNOperationCompleted, userState);
        }
        
        private void OnGetBookByISBNOperationCompleted(object arg) {
            if ((this.GetBookByISBNCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBookByISBNCompleted(this, new GetBookByISBNCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://BullBooksWS.net/GetGenresTable", RequestNamespace="http://BullBooksWS.net/", ResponseNamespace="http://BullBooksWS.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public WSGenre[] GetGenresTable() {
            object[] results = this.Invoke("GetGenresTable", new object[0]);
            return ((WSGenre[])(results[0]));
        }
        
        /// <remarks/>
        public void GetGenresTableAsync() {
            this.GetGenresTableAsync(null);
        }
        
        /// <remarks/>
        public void GetGenresTableAsync(object userState) {
            if ((this.GetGenresTableOperationCompleted == null)) {
                this.GetGenresTableOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetGenresTableOperationCompleted);
            }
            this.InvokeAsync("GetGenresTable", new object[0], this.GetGenresTableOperationCompleted, userState);
        }
        
        private void OnGetGenresTableOperationCompleted(object arg) {
            if ((this.GetGenresTableCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetGenresTableCompleted(this, new GetGenresTableCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://BullBooksWS.net/UpdateRating", RequestNamespace="http://BullBooksWS.net/", ResponseNamespace="http://BullBooksWS.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UpdateRating(string isbn, double newRating) {
            object[] results = this.Invoke("UpdateRating", new object[] {
                        isbn,
                        newRating});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateRatingAsync(string isbn, double newRating) {
            this.UpdateRatingAsync(isbn, newRating, null);
        }
        
        /// <remarks/>
        public void UpdateRatingAsync(string isbn, double newRating, object userState) {
            if ((this.UpdateRatingOperationCompleted == null)) {
                this.UpdateRatingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateRatingOperationCompleted);
            }
            this.InvokeAsync("UpdateRating", new object[] {
                        isbn,
                        newRating}, this.UpdateRatingOperationCompleted, userState);
        }
        
        private void OnUpdateRatingOperationCompleted(object arg) {
            if ((this.UpdateRatingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateRatingCompleted(this, new UpdateRatingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://BullBooksWS.net/AddNewBook", RequestNamespace="http://BullBooksWS.net/", ResponseNamespace="http://BullBooksWS.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool AddNewBook(string isbn, string bookName, string author, string publisher, string synopsis, int numPages, int numChapters, double rating, System.DateTime bookRelease, int[] genres) {
            object[] results = this.Invoke("AddNewBook", new object[] {
                        isbn,
                        bookName,
                        author,
                        publisher,
                        synopsis,
                        numPages,
                        numChapters,
                        rating,
                        bookRelease,
                        genres});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AddNewBookAsync(string isbn, string bookName, string author, string publisher, string synopsis, int numPages, int numChapters, double rating, System.DateTime bookRelease, int[] genres) {
            this.AddNewBookAsync(isbn, bookName, author, publisher, synopsis, numPages, numChapters, rating, bookRelease, genres, null);
        }
        
        /// <remarks/>
        public void AddNewBookAsync(string isbn, string bookName, string author, string publisher, string synopsis, int numPages, int numChapters, double rating, System.DateTime bookRelease, int[] genres, object userState) {
            if ((this.AddNewBookOperationCompleted == null)) {
                this.AddNewBookOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddNewBookOperationCompleted);
            }
            this.InvokeAsync("AddNewBook", new object[] {
                        isbn,
                        bookName,
                        author,
                        publisher,
                        synopsis,
                        numPages,
                        numChapters,
                        rating,
                        bookRelease,
                        genres}, this.AddNewBookOperationCompleted, userState);
        }
        
        private void OnAddNewBookOperationCompleted(object arg) {
            if ((this.AddNewBookCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddNewBookCompleted(this, new AddNewBookCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://BullBooksWS.net/")]
    public partial class WSBook {
        
        private int idField;
        
        private string isbnField;
        
        private string bookNameField;
        
        private string authorField;
        
        private string publisherField;
        
        private string synopsisField;
        
        private int numPagesField;
        
        private int numChaptersField;
        
        private System.DateTime bookReleaseField;
        
        private int[] genresField;
        
        private double ratingField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Isbn {
            get {
                return this.isbnField;
            }
            set {
                this.isbnField = value;
            }
        }
        
        /// <remarks/>
        public string BookName {
            get {
                return this.bookNameField;
            }
            set {
                this.bookNameField = value;
            }
        }
        
        /// <remarks/>
        public string Author {
            get {
                return this.authorField;
            }
            set {
                this.authorField = value;
            }
        }
        
        /// <remarks/>
        public string Publisher {
            get {
                return this.publisherField;
            }
            set {
                this.publisherField = value;
            }
        }
        
        /// <remarks/>
        public string Synopsis {
            get {
                return this.synopsisField;
            }
            set {
                this.synopsisField = value;
            }
        }
        
        /// <remarks/>
        public int NumPages {
            get {
                return this.numPagesField;
            }
            set {
                this.numPagesField = value;
            }
        }
        
        /// <remarks/>
        public int NumChapters {
            get {
                return this.numChaptersField;
            }
            set {
                this.numChaptersField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime BookRelease {
            get {
                return this.bookReleaseField;
            }
            set {
                this.bookReleaseField = value;
            }
        }
        
        /// <remarks/>
        public int[] Genres {
            get {
                return this.genresField;
            }
            set {
                this.genresField = value;
            }
        }
        
        /// <remarks/>
        public double Rating {
            get {
                return this.ratingField;
            }
            set {
                this.ratingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://BullBooksWS.net/")]
    public partial class WSGenre {
        
        private int genreIDField;
        
        private string genreNameField;
        
        /// <remarks/>
        public int GenreID {
            get {
                return this.genreIDField;
            }
            set {
                this.genreIDField = value;
            }
        }
        
        /// <remarks/>
        public string GenreName {
            get {
                return this.genreNameField;
            }
            set {
                this.genreNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetBookByISBNCompletedEventHandler(object sender, GetBookByISBNCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetBookByISBNCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetBookByISBNCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WSBook Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WSBook)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetGenresTableCompletedEventHandler(object sender, GetGenresTableCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetGenresTableCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetGenresTableCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WSGenre[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WSGenre[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void UpdateRatingCompletedEventHandler(object sender, UpdateRatingCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateRatingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateRatingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void AddNewBookCompletedEventHandler(object sender, AddNewBookCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddNewBookCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddNewBookCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591