<%@ Page Title="" Language="C#" MasterPageFile="~/Toolbar.Master" AutoEventWireup="true" CodeBehind="AdminPage.aspx.cs" Inherits="BullBooks.AdminPage" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">

</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    

    <div class="OuterBox AdminOuterBox">
        <h1>ADMIN PAGE</h1>
        <div class="AdminUserSearch">
        <asp:TextBox runat="server" ID="SearchBar" placeholder="Search for a user" TextMode="SingleLine"></asp:TextBox>
        <select runat="server" id="SearchBy">
            <option value="Id">id</option>
            <option value="Username">username</option>
            <option value="Email">email</option>
            <option value="Alias">alias</option>
        </select>
            <asp:ImageButton ID="SearchSubmit" runat="server" ImageUrl="../ControlImages/send.png" OnClick="SearchSubmit_Click" />
            <div class="UserSearchCheckBox">
                <asp:CheckBoxList runat="server" ID="UserType">
                <asp:ListItem Text="Author" Value="author"></asp:ListItem>
                <asp:ListItem Text="Admin" Value="admin"></asp:ListItem>
                <asp:ListItem Text="Publisher" Value="publisher"></asp:ListItem>
            </asp:CheckBoxList>
            <asp:CheckBox runat="server" ID="ToggleTypeSearch" Text="Toggle search by user type" />
            </div>
            
        </div>
        <asp:GridView CssClass="UserTable" OnRowDeleting="DeleteUser" OnRowCancelingEdit="CancelEdit" OnRowUpdating="RowUpdating" OnRowEditing="EditUser" AutoGenerateEditButton="true" OnRowCreated="RemoveColumns" AutoGenerateDeleteButton="true" autOnRowCreated="RemoveColumns"  runat="server" ID="UserTable" AutoGenerateColumns="true"></asp:GridView>
    </div>
</asp:Content>
