<%@ Page Title="" Language="C#" MasterPageFile="~/Toolbar.Master" AutoEventWireup="true" CodeBehind="AdminPage.aspx.cs" Inherits="BullBooks.AdminPage" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">

</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="OuterBox AdminOuterBox">
    <asp:GridView CssClass="UserTable" OnRowDeleting="DeleteUser" OnRowCancelingEdit="CancelEdit" OnRowUpdating="RowUpdating" OnRowEditing="EditUser" AutoGenerateEditButton="true" OnRowCreated="RemoveColumns" AutoGenerateDeleteButton="true" autOnRowCreated="RemoveColumns"  runat="server" ID="UserTable" AutoGenerateColumns="true"></asp:GridView>
    </div>
</asp:Content>
